### ISSUE TITLE
Question on including this file

### ISSUE THREAD

**Issue by shadowlion** [HeyAri/Center-4-Certification#1]
What's the point of this /includes file - "now.fn"? what's the function of it?

**Comment by HeyAri** [comment]
I think it is for the date on the certificate? The only other date is in the footer

**Comment by shadowlion** [comment]
Ok - I think I will remove it - PHP has a good way to obtain the current date data
- see line 224 of index.php - translates to line 31 of certificate.php
- see line 10 of footer.php - only one line to update footer ;)
