### ISSUE TITLE
Alignment Issues

### ISSUE THREAD

**Issue by shadowlion** [HeyAri/Center-4-Certification#12]
Some of the stamps on the picture templates of the certificates aren't center-aligned. I found it when looking at the Curly and Ornate images. Can you verify?

**Comment by HeyAri** [comment]
Yes, the wax stamp is supposed to be hand stamped and could be off center

Ari
513.348.9120

On Jun 11, 2017, at 10:59 AM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:


Some of the stamps on the picture templates of the certificates aren't center-aligned. I found it when looking at the Curly and Ornate images. Can you verify?
