### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by HeyAri** [HeyAri/Center-4-Certification#17]
In the last reset, we lost your recaptcha additions. In replacing it, can we get rid of the recaptcha promo tag in the bottom right?

**Comment by shadowlion** [comment]
Can you send me via email your keys? I wanna put it in and test the recaptcha. [This is how to get those keys](https://www.google.com/recaptcha/admin#list).

**Comment by HeyAri** [comment]
site key
6LegwyUUAAAAAFMZkIdllyCloNdsdKExfzW3DQPP

Private key
6LegwyUUAAAAABIKijkI-jxo-wWH1CjHFcTQASlb

Thanks!

Ari
513.348.9120

On Jun 17, 2017, at 7:23 AM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you send me via email your keys? I wanna put it in and test the recaptcha. This is how to get those keys.<https://www.google.com/recaptcha/admin#list>.

**Comment by shadowlion** [comment]
Check to see it works now, and close issue.

**Comment by HeyAri** [comment]
Works I think!

**Comment by HeyAri** [comment]
Still getting lots of fake ones. Maybe the invisible captcha is not enough. I guess we need to tie it into the human buttons I have.


On Jun 17, 2017, at 1.30 P, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:


Check to see it works now, and close issue.
