### ISSUE TITLE
Radio buttons reappeared?

### ISSUE THREAD

**Issue by HeyAri** [HeyAri/Center-4-Certification#18]
Seems like the radio buttons are back next to the certificate thumbnails. Code didn't change, something new with the browsers?

**Comment by shadowlion** [comment]
For some reason, you’re not adding all the assets over FTP - I had in “assets/css” a css override called style.css, but it was missing when I checked the site (it had the code to hide the radio buttons).

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
Got it, thx!
