### ISSUE TITLE
Input field after dropdown

### ISSUE THREAD

**Issue by shadowlion** [HeyAri/Center-4-Certification#9]
Is there a reason why we have pushback on the "you chose:" input? I figured to make it readonly so they can't change what they chose from the dropdown, but you keep deleting that entry.

**Comment by HeyAri** [comment]
Yes, the idea is they can enter their own if it is not in the list.

Ari
513.348.9120

On Jun 8, 2017, at 11:49 AM, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a reason why we have pushback on the "you chose:" input? I figured to make it readonly so they can't change what they chose from the dropdown, but you keep deleting that entry.

**Comment by shadowlion** [comment]
Would it be better if we make a "customize your own" in the dropdown, and use jQuery to unhide that input when the value of that dropdown changes?

**Comment by HeyAri** [comment]
If anything, I think a customize your own that sends the cursor to that field? It seems to work fine now. People have been using it.



On Jun 8, 2017, at 12.22 P, Justin Chiou <notifications@github.com<mailto:notifications@github.com>> wrote:


Would it be better if we make a "customize your own" in the dropdown, and use jQuery to unhide that input when the value of that dropdown changes?

**Comment by shadowlion** [comment]
Ok
